server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://comiclibrary.c96wceknz5dj.ap-southeast-1.rds.amazonaws.com:3306/comic_library
    username: admin
    password: Khai1211!

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: redis-13005.c252.ap-southeast-1-1.ec2.redns.redis-cloud.com
      port: 13005
      password: YUGlni8un2dWM5NgFoEITHD5g0w1uuUg
      username: default
    web:
      pageable:
        default-page-size: 20
        one-indexed-parameters: true
        max-page-size: 50

  security:
    oauth2:
      client:
        registration:
          google-login:
            provider: google
            client-id: 49619057630-ij5tirenev88rlsull9dtbr3jher6mm3.apps.googleusercontent.com
            client-secret: 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

api:
  prefix: /api

jwt:
  access-token-expiration-in-seconds: 600 #10 minutes (600s) = 6 * 60
  refresh-token-expiration-in-seconds: 7776000 #90 days (7776000s) = 90 * 24 * 60 * 60
  base64-secret: xqWM9YRbhgqWNY9REd4RW47o/kZRkOkQrzg1qdMBVfiXErOHpT6UTVwoUnNIZLIDaFiatwVbNgyjx/iMYbNkKQ==

logging:
  level:
    root: INFO
    vn.khaiduong.comiclibrary: TRACE
  file:
    name: log/dev.log