server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/comic_library
    username: root
    password: Khai_1211

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    web:
      pageable:
        default-page-size: 20
        one-indexed-parameters: true
        max-page-size: 50

api:
  prefix: /api

jwt:
  access-token-expiration-in-seconds: 600 #10 minutes (600s) = 6 * 60
  refresh-token-expiration-in-seconds: 7776000 #90 days (7776000s) = 90 * 24 * 60 * 60
  base64-secret: xqWM9YRbhgqWNY9REd4RW47o/kZRkOkQrzg1qdMBVfiXErOHpT6UTVwoUnNIZLIDaFiatwVbNgyjx/iMYbNkKQ==
  refresh-token-cookie-name: refresh_token

logging:
  level:
    root: INFO
    vn.khaiduong.comiclibrary: TRACE
  file:
    name: log/dev.log