server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springsecuritydemo
    username: root
    password: Khai_1211

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

api:
  prefix: /api

jwt:
  expiration-in-seconds: 86400 #1 day (86400s) = 24 * 60 * 60
  base64-secret: zNmgOnudAdPIQPXlnzsTaTxC8bOCGaF/PGHSxOlJXCnYDRMj3fC5qil7+NtMK6+e liTNyZwj3D0sVgGCfB/pxg==
  claim-name: khaiduong

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace